export interface User {
    _id: String,
    userCreationTimestamp: Date,
    premium: Boolean,
    premiumDate: Date,
    isBanned: Boolean,
    banData: Date,
    banReason: String,
    aboutme: String,
    balance: Number,
    lastDaily: Date,
    marriedWith: String,
    marriedDate: Date,
    cantMarry: Boolean,
    repCount: Number,
    lastRep: Date,
    background: String,
    backgrounds: String[],
    premiumType: String,
    language: String,
    mask: String,
    masks: String[],
    layout: String
}